automation:
  - alias: "Send chat message to Sterling"
    trigger:
      platform: state
      entity_id: input_text.ha_chat_input
    condition:
      - condition: template
        value_template: "{{ trigger.from_state.state != '' }}"
    action:
      - service: rest_command.send_ha_chat
      - wait_for_trigger:
          platform: state
          entity_id: sensor.ai_response
      - service: input_text.set_value
        target:
          entity_id: input_text.ha_chat_input
        data:
          value: ""
