# Phase 6: Multi-Agent Prediction Layer

sensor:
  - platform: statistics
    name: "Garage Door Open Duration Avg 24h"
    entity_id: binary_sensor.garage_door_open
    state_characteristic: change
    max_age:
      hours: 24
    unique_id: garage_door_open_duration_avg_24h

  - platform: template
    sensors:
      garage_door_anomaly:
        friendly_name: "Garage Door Anomaly Detected"
        value_template: >
          {% set current_open_duration = (now() - states.binary_sensor.garage_door_open.last_changed).total_seconds() if is_state('binary_sensor.garage_door_open', 'on') else 0 %}
          {% set avg_open_duration = states('sensor.garage_door_open_duration_avg_24h') | float(0) %}
          {{ 'true' if current_open_duration > (avg_open_duration * 2) and current_open_duration > 3600 else 'false' }}
        device_class: problem
        unique_id: garage_door_anomaly_sensor
        icon: mdi:alert-octagon
