name: Auto Agent
on:
  issue_comment:
    types: [created]
  push:
    branches: [main]
  schedule:
    - cron: '0 4 * * *'  # Daily at 4 AM UTC

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  auto-agent:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '/codex run')) ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'schedule')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Make agent executable
        run: chmod +x tools/agent.py
        
      - name: Run Sterling Agent
        run: python tools/agent.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_CLOUD_PROJECT: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
          REGION: ${{ secrets.REGION }}
          
      - name: Comment on issue (if triggered by issue comment)
        if: github.event_name == 'issue_comment'
        uses: actions/github-script@v7
        with:
          script: |
            const issue_number = context.issue.number;
            const comment_body = `
            🤖 **Sterling Agent Execution Complete**
            
            Agent run triggered by \`/codex run\` command.
            
            **Execution Summary:**
            - ✅ Linting completed
            - ✅ Tests executed
            - ✅ Code analysis performed
            - ✅ Infrastructure checks completed
            
            Check the Actions tab for detailed logs and results.
            
            *Timestamp: ${new Date().toISOString()}*
            `;
            
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: comment_body
            });
            
      - name: Upload agent report
        uses: actions/upload-artifact@v3
        with:
          name: agent-report-${{ github.run_number }}
          path: agent_report_*.json
          if-no-files-found: ignore