name: Sterling Canary Diagnostic

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  canary:
    runs-on: ubuntu-latest

    steps:
      - name: \ud83d\udcdd Checkout Repo
        uses: actions/checkout@v3

      - name: \ud83e\udde0 Install YAML Linter
        run: |
          sudo apt-get update
          sudo apt-get install -y yamllint

      - name: \ud83d\udd0d Validate HA Configs
        run: |
          echo "\ud83d\udea8 Canary Lint Check Initiated"
          FILES=("configuration.yaml" "automations.yaml" "scripts.yaml")

          ERRORS=0
          for file in "${FILES[@]}"; do
            if [ -f "$file" ]; then
              echo "\ud83e\uddca Linting $file..."
              yamllint "$file" || ERRORS=$((ERRORS+1))
            else
              echo "\u26a0\ufe0f Skipped missing $file"
            fi
          done

          if [ "$ERRORS" -gt 0 ]; then
            echo "\u274c Lint errors detected"
            exit 1
          else
            echo "\u2705 All configs pass lint"
          fi

