name: "🤖 Codex Agent Automation"

on:
  issue_comment:
    types: [created]
  push:
    branches: [ main ]
  schedule:
    - cron: '0 4 * * *'

jobs:
  run-agent:
    if: >
      github.event_name == 'push' ||
      (github.event_name == 'issue_comment' &&
       contains(github.event.comment.body, '/codex run'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai PyGithub

      - name: Run Codex agent
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_APP_ID:      ${{ secrets.GITHUB_APP_ID }}
          GITHUB_PRIVATE_KEY: ${{ secrets.GITHUB_PRIVATE_KEY }}
          GITHUB_REPOSITORY:  ${{ github.repository }}
          ISSUE_NUMBER:      ${{ github.event.issue.number || '' }}
        run: |
          python tools/agent.py
