name: Sterling Canary Diagnostic

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  run_canary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run HA Config Validation
        run: |
          docker run -v "${{ github.workspace }}:/config" --rm \
          ghcr.io/home-assistant/home-assistant:stable --script check_config

      - name: Run Canary Prompt via Codex CLI
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          npm install -g @openai/codex
          codex exec --full-auto "Sterling, run full system diagnostic and confirm access to HA API, YAML, input_boolean.canary_test, and Codex write. Return status block."

      - name: Report Canary Trigger
        run: echo "✅ Sterling Canary diagnostic triggered from GitOps pipeline."
