name: CI
on: [push]
permissions:
  contents: read
jobs:
  lint-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: shellcheck scripts/*.sh
  python-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [adaptive_router, concord_engine, repair_agent]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install -r src/requirements.txt
      - run: pytest tests/test_${{ matrix.module }}.py
  build-addon:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # ---------------------------------------------
      # Remove the old `docker build` invocation:
      # ---------------------------------------------

      # 1) Enable QEMU so we can emulate Home Assistant’s target platforms
      - name: Set up QEMU for multi-platform builds
        uses: docker/setup-qemu-action@v2

      # 2) Enable Buildx (no daemon needed)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3) Build the add-on with Buildx
      - name: Build Sterling OS add-on
        uses: docker/build-push-action@v4
        with:
          context: addons/sterling_os
          load: true    # so it’s available locally for tests
          push: false   # we don’t want to push to a registry

      - name: Run tests
        run: pytest -q
