name: CI
on: [push]
permissions:
  contents: read
jobs:
  lint-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ShellCheck
        run: shellcheck -e SC2181 scripts/*.sh
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Install editable package
        run: pip install -e .
      - name: Scaffold phase stubs
        run: python scripts/scaffold_phases.py
      - name: Run pytest
        run: python -m pytest tests/test_phase_* -q
  build-addon:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Sterling OS add-on
        uses: docker/build-push-action@v5
        with:
          context: .
          file: addons/sterling_os/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
