name: CI
on: [push]
permissions:
  contents: read
jobs:
  lint-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ShellCheck
        run: shellcheck scripts/*.sh
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - name: Run pytest modules tests
        env:
          # include your inner package dir so "import modules…" works
          PYTHONPATH: ${{ github.workspace }}/sterling_ha_project
        run: pytest modules tests -q
  build-addon:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Sterling OS add-on
        uses: docker/build-push-action@v5
        with:
          context: addons/sterling_os
          platforms: linux/amd64,linux/arm64
          push: false
