name: Deploy Router Stack

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt
      - run: pytest -q
      - run: ./scripts/deploy.sh
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          REGION: us-central1
