name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker Build Test
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./addons/sterling_os/Dockerfile
          push: false
