name: GCP Workflow

'on':
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Google Cloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Set environment variables
      - name: Set Environment Variables
        run: |
          echo "PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}" >> $GITHUB_ENV
          echo "GOOGLE_CLOUD_PROJECT=${{ secrets.GCP_PROJECT_ID }}" >> $GITHUB_ENV

      # Authenticate with GCP
      - name: Authenticate with GCP
        run: |
          gcloud config set project $PROJECT_ID
          gcloud auth activate-service-account --key-file=${{ secrets.GCP_SA_KEY }}

      # Replace environment variables in files or commands
      - name: Replace $PROJECT in Commands
        run: |
          gcloud builds submit --project=$PROJECT_ID
