name: Sterling GitOps Deploy
on:
  push:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate config
        run: |
          docker run -v "${{ github.workspace }}:/config" --rm ghcr.io/home-assistant/home-assistant:stable --script check_config

  deploy:
    needs: validate
    runs-on: ubuntu-latest
    env:
      HA_URL: ${{ secrets.HA_URL }}
      HA_TOKEN: ${{ secrets.HA_LONG_LIVED_TOKEN }}
    steps:
      - name: Trigger Git Pull add-on
        run: |
          curl -X POST "https://${HA_URL}/api/services/hassio/addon_restart" -H "Authorization: Bearer ${HA_TOKEN}" -H "Content-Type: application/json" -d '{"addon":"core_git_pull"}'
      - name: Restart HA Core
        run: |
          curl -X POST "https://${HA_URL}/api/services/homeassistant/restart" -H "Authorization: Bearer ${HA_TOKEN}" -H "Content-Type: application/json" -d '{}'
