name: Sterling Sentinel Monitor

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  sentinel:
    runs-on: ubuntu-latest

    steps:
      - name: \ud83d\udcdd Checkout Repo
        uses: actions/checkout@v3

      - name: \ud83e\udde0 Lint Check
        run: |
          sudo apt-get update && sudo apt-get install -y yamllint

          echo "\ud83d\udd10 Running Sentinel config sweep"
          yamllint . || echo "\u26a0\ufe0f Lint warnings, but continuing..."

