name: Sterling YAML Lint

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install YAML Linter
        run: |
          sudo apt-get update
          sudo apt-get install -y yamllint
      - name: Validate YAML
        run: |
          yamllint -c .yamllint homeassistant_config
